language: go
go:
  - "1.11"
  - "1.11.x"
env:
  - GO111MODULE=on
notifications:
  email:
    recipients:
      - 1156143589@qq.com
      - wuxiaoshen@shu.edu.cn
    on_success: change # default: change
    on_failure: always # default: always
before_install:
  - go test -cpu=1,2,4 -v -tags integration ./...
  - go vet $(go list ./... | grep -v /vendor/)

script:
  - go test -race  ./... -coverprofile=coverage.txt -covermode=atomic

after_success:
  - bash <(curl -s https://codecov.io/bash) -t b51e7150-c16a-4651-8885-06d44bee1ac8
